name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]

env:
  REGISTRY: veterinaryapp.azurecr.io  # Cambia por tu ACR
  IMAGE_NAME: veterinary-app
  AZURE_WEBAPP_NAME: veterinary-app   # Cambia por tu nombre de App Service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push auth-service
      uses: docker/build-push-action@v3
      with:
        context: ./services/auth-service
        file: ./services/auth-service/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-auth-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-auth-service:${{ github.sha }}

    - name: Build and push pets-service
      uses: docker/build-push-action@v3
      with:
        context: ./services/pets-service
        file: ./services/pets-service/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-pets-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-pets-service:${{ github.sha }}

    - name: Build and push appointments-service
      uses: docker/build-push-action@v3
      with:
        context: ./services/appointments-service
        file: ./services/appointments-service/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-appointments-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-appointments-service:${{ github.sha }}

    - name: Build and push notifications-service
      uses: docker/build-push-action@v3
      with:
        context: ./services/notifications-service
        file: ./services/notifications-service/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-notifications-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-notifications-service:${{ github.sha }}

    - name: Build and push web-client
      uses: docker/build-push-action@v3
      with:
        context: ./clients/web-client
        file: ./clients/web-client/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web-client:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web-client:${{ github.sha }}

  deploy-to-azure:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    needs: [build-and-push]
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-container-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-auth-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-pets-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-appointments-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-notifications-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web-client:latest
        configuration-file: docker-compose.prod.yml